framework:
    rate_limiter:
        username_ip_login:
            policy: token_bucket
            limit: 5
            rate: { interval: '5 minutes' }

        ip_login:
            policy: sliding_window
            limit: 50
            interval: '15 minutes'

services:
    app.login_rate_limiter:
        class: Symfony\Component\Security\Http\RateLimiter\DefaultLoginRateLimiter
        arguments:
            $globalFactory: '@limiter.ip_login'
            $localFactory: '@limiter.username_ip_login'

security:
    enable_authenticator_manager: true
    password_hashers:
        App\Entity\User:
            algorithm: auto

    providers:
        app_user_provider:
            entity:
                class: App\Entity\User
                property: email
    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
            login_throttling:
                max_attempts: 3
                interval: '15 minutes'
                limiter: app.login_rate_limiter
        main:
            lazy: true
            provider: app_user_provider
            login_throttling:
                max_attempts: 3
                interval: '15 minutes'
                limiter: app.login_rate_limiter
            json_login:
                check_path: /login
                username_path: email
                password_path: password
            custom_authenticators: 
                - App\Security\TokenAuthenticator
            entry_point: App\Security\EntryPointAuth
            stateless: true

    access_control:
        - { path: ^/profile, roles: ROLE_USER }
        - { path: ^/books, roles: ROLE_USER }
