# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices.html#use-parameters-for-application-configuration
parameters:

services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

    # makes classes in src/ available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    App\:
        resource: '../src/'

    # add more service definitions when explicit configuration is needed
    # please note that last definitions always *replace* previous ones

    Symfony\Component\HttpFoundation\Request:
    
    Symfony\Component\Serializer\Encoder\JsonEncoder:
        class: Symfony\Component\Serializer\Encoder\JsonEncoder

    Symfony\Component\Serializer\SerializerInterface:
        class: Symfony\Component\Serializer\Serializer
        arguments: [
            ["@Symfony\\Component\\Serializer\\Normalizer\\ObjectNormalizer"],
            ["@Symfony\\Component\\Serializer\\Encoder\\JsonEncoder"]
        ]

    App\Controller\RegisterController:
        public: true
        arguments: [
            "@Symfony\\Component\\Validator\\Validator\\ValidatorInterface",
            "@Symfony\\Component\\Serializer\\SerializerInterface",
            "@Symfony\\Component\\HttpFoundation\\Request",
            "@App\\Repository\\UserRepository",
            "@Symfony\\Component\\DependencyInjection\\ContainerInterface"
        ]
        tags: ['controller.service_arguments']

    Symfony\Component\PasswordHasher\Hasher\UserPasswordHasherInterface:
        class: Symfony\Component\PasswordHasher\Hasher\UserPasswordHasher
        public: true

    App\Security\EntryPontAuth:
        class: App\Security\EntryPointAuth

    App\Entity\User:
        arguments: [
            "@Symfony\\Component\\PasswordHasher\\Hasher\\UserPasswordHasherInterface"
        ]